services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    container_name: laravel_app
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - storage_data:/var/www/storage

  webserver:
    image: ghcr.io/${GITHUB_REPOSITORY}-nginx:latest
    container_name: nginx_app
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  storage_data: