services:
  # Nginx Web Server
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: noor-hotel-nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always
    networks:
      - noor-hotel-network
      - bqems-app_bqems-network

  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noor-hotel-app
    volumes:
      - ./.env:/var/www/.env
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - noor-hotel-network

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: noor-hotel-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: noor_hotel
      POSTGRES_USER: nooor
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - noor-hotel-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: noor-hotel-redis
    restart: always
    networks:
      - noor-hotel-network

networks:
  noor-hotel-network:
    driver: bridge
  bqems-app_bqems-network:
    external: true

volumes:
  postgres_data:
